version: '3.8'

services:
  mysql:
    image: mysql:8.0.34
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd!2023
      MYSQL_DATABASE: onlineShop
    ports:
      - "3307:3306"
    networks:
      - shopnet
    volumes:
      - mysql-data:/var/lib/mysql

  onlineshoprestapi:
    build: .
    container_name: onlineshoprestapi
    volumes:
      - /home/parsa/onlineShopApi/config/:/app/config/
    depends_on:
      - mysql
    ports:
      - "8090:9004"
    networks:
      - shopnet
    env_file:
      - .env
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9004/health"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  shopnet:

volumes:
  mysql-data:
