basePath: /
host: localhost:8090
info:
  contact:
    email: example@example.com
    name: Support
  description: Online Shop REST API
  license:
    name: MIT
  termsOfService: http://swagger.io/terms/
  title: Product API
  version: "1.0"
paths:
  /api/v1/health/health:
    get:
      description: این یک سرویس تست است
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: تست سرویس
      tags:
      - Test
swagger: "2.0"
