name: Build and Deploy with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate .env files (root & docker/.env)
        run: |
          # ساخت .env روت پروژه
          echo "APP_ENV=production" > .env
          echo "PORT=${{ secrets.API_PORT }}" >> .env

          # ساخت docker/.env با مقادیر مخفی از Secrets
          mkdir -p docker
          echo "ELASTIC_VERSION=${{ secrets.ELASTIC_VERSION }}" > docker/.env
          echo "ELASTIC_PASSWORD=${{ secrets.ELASTIC_PASSWORD }}" >> docker/.env
          echo "KIBANA_SYSTEM_PASSWORD=${{ secrets.KIBANA_SYSTEM_PASSWORD }}" >> docker/.env
          echo "FILEBEAT_INTERNAL_PASSWORD=${{ secrets.FILEBEAT_INTERNAL_PASSWORD }}" >> docker/.env

      - name: Archive project files
        run: tar czf project.tar.gz src go.mod go.sum Dockerfile docker-compose.yml docs .env docker/.env

      - name: Copy project to VPS via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          port: ${{ secrets.VPS_PORT }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          source: "project.tar.gz"
          target: "/home/parsa"

      - name: Deploy and Run Docker Compose on VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          port: ${{ secrets.VPS_PORT }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /home/parsa
            rm -rf CleanRestApi || true
            mkdir -p CleanRestApi
            tar xzf project.tar.gz -C CleanRestApi
            cd CleanRestApi
            docker compose down || true
            docker compose up -d --build
            # لاگ‌های داکر را پاک کن (اختیاری)
            sh -c "truncate -s 0 /var/lib/docker/containers/*/*-json.log" || true
            # پاکسازی فایل‌ها (اختیاری)
            cd /home/parsa
            rm -f project.tar.gz

