name: Build and Deploy with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Archive project files (exclude the archive itself)
        run: tar --exclude=project.tar.gz -czf project.tar.gz .

      - name: Copy project to VPS via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 127.0.0.1
          port: 2222
          username: parsa
          password: parsa
          source: "project.tar.gz"
          target: "/home/parsa"

      - name: Deploy and Run Docker Compose on VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 202.133.88.175
          port: 2026
          username: parsa
          password: 123
          script: |
            cd /home/parsa
            rm -rf CleanRestApi || true
            mkdir -p CleanRestApi
            tar xzf project.tar.gz -C CleanRestApi
            cd CleanRestApi
            docker compose down || true
            docker compose up -d --build
