name: Build and Deploy with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate .env file
        run: |
          echo "APP_ENV=production" > .env
          echo "PORT=${{ secrets.API_PORT }}" >> .env

      - name: Archive project files
        run: tar czf project.tar.gz src go.mod go.sum Dockerfile docker-compose.yml docs .env

      - name: Copy project to VPS via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          port: ${{ secrets.VPS_PORT }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          source: "project.tar.gz"
          target: "/home/parsa"

      - name: Deploy and Run Docker Compose on VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          port: ${{ secrets.VPS_PORT }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /home/parsa
            rm -rf CleanRestApi || true
            mkdir -p CleanRestApi
            tar xzf project.tar.gz -C CleanRestApi
            cd CleanRestApi
            mkdir -p config
            docker compose down || true
            docker compose up -d --build

            sh -c "truncate -s 0 /var/lib/docker/containers/*/*-json.log"
            cd /home/parsa
            docker system prune -a
            rm -rf CleanRestApi
            rm -f project.tar.gz
