name: Simple SSH HelloWorld

on:
  push:
    branches:
      - main

jobs:
  helloworld-job:
    runs-on: ubuntu-latest

    steps:
      - name: Create helloworld.txt
        run: echo "Hello, world from GitHub Actions!" > helloworld.txt

      - name: Copy helloworld.txt to VPS via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 202.133.88.175
          port: 2026
          username: parsa
          password: 123
          source: "helloworld.txt"
          target: "/home/parsa/"
